# Generated by Django 5.1.7 on 2025-03-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot_start_time", models.DateTimeField(db_index=True)),
                ("slot_end_time", models.DateTimeField()),
                ("capacity_used", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["slot_start_time"],
                "indexes": [
                    models.Index(
                        fields=["slot_start_time"], name="slots_slot_slot_st_5bb784_idx"
                    )
                ],
            },
        ),
    ]
