# Generated by Django 5.1.7 on 2025-03-27 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("slots", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_attendees", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("CONFIRMED", "Confirmed")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReservationSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_slots",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_slots",
                        to="slots.slot",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reservation",
            name="slots",
            field=models.ManyToManyField(
                through="reservations.ReservationSlot", to="slots.slot"
            ),
        ),
        migrations.AddIndex(
            model_name="reservationslot",
            index=models.Index(
                fields=["reservation"], name="reservation_reserva_51fc17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservationslot",
            index=models.Index(fields=["slot"], name="reservation_slot_id_8fd963_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="reservationslot",
            unique_together={("reservation", "slot")},
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["user"], name="reservation_user_id_56b0f8_idx"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["status"], name="reservation_status_f1a03a_idx"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["created_at"], name="reservation_created_fddb5a_idx"
            ),
        ),
    ]
